### ISSUE TITLE
공통 Response Wrapper  관련 이슈

### ISSUE THREAD

**Issue by kh0712** [mash-up-kr/Elegant_Spring_Family_Search#12]
서버의 모든 응답을 감쌀 Custom Response Wrapper 이슈입니다.

1. Custom Response Wrapper 가 필요할지?

2. 필요하지 않다면 어떻게 감쌀지? (Response Entity 등)

3. 필요하다면 어떤 필드가 필요할지? (code, message, 예외를 어떻게 담을지?, 페이징 관련)

**Comment by jongnan** [comment]
솔직히 이건 클라와 상의해봐야 할 문제라고 생각하고 지금부터 모든 응답을 정의해서 내려줄 필요까지는 없어 보입니다.

이것도 로깅과 관련해서 같이 나중에 개발하면 좋을 것 같아보입니다.
