### ISSUE TITLE
로깅 방법 정하기

### ISSUE THREAD

**Issue by kh0712** [mash-up-kr/Elegant_Spring_Family_Search#13]
1. 시기 : 로깅 구현은 서비스의 프로토타입이 완성되고 나서 구현해야 할까요?

2. 외부 라이브러리에 slf4j가 있는데 롬복 @Slf4j 어노테이션으로 사용할까요?
    그거때문에 롬복 받기보다는 그냥 주입받아서 써도 괜찮을 것같습니다.

**Comment by jongnan** [comment]
1. 로깅의 경우 프로토타입이 끝나고 따로 구현하는 것이 좋을것 같습니다.

2. 굳이 롬복을 쓸 필요까진 없어보이긴하네요!
