### ISSUE TITLE
검색 쿼리 쿼리 빌딩 및 Boost parameter 책임 분리 

### ISSUE THREAD

**Issue by kh0712** [mash-up-kr/Elegant_Spring_Family_Search#15]
Search Service에서 쿼리 빌딩은 따로 뺄 필요가 없을 것 같습니다.
쿼리는 어느 필드에 대해 검색할 지를 빌더 패턴을 이용해 빌딩하게 되는데
키워드 검색과 카테고리 검색은 검색 대상 필드가 상이하고, 빌더 패턴을 사용하는 특성상 따로 분리하기가 어려워 보입니다.

다만 Boost는 파라미터는 튜닝이 필요한 값이라서 Boost 값 자체는 설정 파일로 빼고 싶은데 
@Value를 이용해서 서비스에서 직접 주입받기 Vs 설정값을 들고 있는 빈으로 분리해서 빈에서 @Value로 주입받을지 고민입니다.
혹시 다른 방법이 있을까요?

**Comment by jongnan** [comment]
혹시 대략적인 코드도 볼 수 있을까요?

**Comment by kh0712** [comment]
Search service에 있습니다

**Comment by jongnan** [comment]
근데 `.matchQuery("shop_name", keyword).boost(5.0f))` 이 값들은 SearchService에서만 사용하는거 아닌가요?

만약 여기서만 사용하는 값이라면 그냥 상수로 정의해서 가지고 있는게 더 좋을것 같아보이기도 하네요!

**Comment by kh0712** [comment]
검색 서비스에서만 사용하지만 검색 결과를 결정하는 서버 차원의 중요한 값이기 때문에 따로 빈으로 빼서 api나 config 서버를 이용해 동적으로 변경하는 방법도 고려하고 있습니다
