### ISSUE TITLE
메시지 큐 선정

### ISSUE THREAD

**Issue by jongnan** [mash-up-kr/Elegant_Spring_Family_Search#16]
1. Kafka
    > Amazon Managed Streaming for Apache Kafka (No free-tier)

2. rabbitMQ
    > Amazon MQ (free-tier)

**Comment by jongnan** [comment]
### 메시지 큐를 사용하는 목적
* 가게의 정보가 변경되었을 시에 Elasticsearch에 이를 반영
* 변경이 이루어졌을 시에 신속하게 변경되는 것이 핵심
* 가게의 변동 사항만 받으면 되므로 따로 메시지를 가공할 필요도 없어보임

### 선택한 메시지 큐의 장단점

#### Kafka
* Kafka의 장점은 고가용성 구성의 속도가 굉장히 빠름, 따라서 빠른 검색을 위해 카프카를 사용하는 것은 굉장히 좋은 선택
* 또한, 메시지 가공도 필요없으므로 커넥터를 사용하여 바로 Elasticsearch에 주입이 가능할 것으로 보임
* 하지만, Kafka의 경우 AWS에서 MSK를 통해서 쉽게 HA한 서버를 구성할 수 있으나, 여러개의 브로커와 게이트웨이 인스턴스를 띄워야 하기 때문에 비용이 만만치 않을 것으로 예상

#### RabbitMQ
* 카프카에 비해 속도는 느리지만 굉장히 성숙한 메시지 큐
* Logstash를 통해 메시지 가공하고 바로 Elasticsearch로 넣을 수 있음
* 무엇보다도 AWS에서 프리티어가 존재하므로 공짜로 사용 가능

### 결론
* 인스턴스에 카프카를 수동으로 띄울 수 있겠지만 이 또한 비용이 발생하므로 카프카를 사용하기 위해서는 비용 발생
* 현재 주어진 상황에서는 카프카는 단순히 속도만 빠를뿐 큰 장점이 보이지 않음
* 그러므로 RabbitMQ를 사용하여 진행

**Comment by kh0712** [comment]
기능 구현만 봤을때는 어느 메세지 큐를 사용해도 별 문제없을 것 같네요 좋습니당
