### ISSUE TITLE
메시지 큐 리스너는 어느 패키지에 들어가야 할까요?

### ISSUE THREAD

**Issue by jongnan** [mash-up-kr/Elegant_Spring_Family_Search#21]
### 직면한 문제
* 과연 메시지 리스너는 어느 패키지로 들어가는 것이 맞는 것일까?

### 개인적인 생각
* 먼저 도메인쪽에 넣어놨는데, 아직 도메인 패키지에 대한 이해도가 떨어져서 맞는지는 잘 모르겠습니다.
* 만약 이런 컴포넌트만 따로 모아두는 새로운 패키지를 만들어야 할까요?

---

여러분들의 의견이 필요할 것 같습니다!

**Comment by kh0712** [comment]
도메인 - 메세지에 들어가면 충분할 것같습니다. 아직 서비스 패키지는 redundant 한 것 같네요

**Comment by jongnan** [comment]
모든 서비스 파일은 서비스 패키지에 들어가는게 맞지 않나요??

**Comment by lee-garden** [comment]
개인적으로는 서비스 패키지에 리슨 하는 부분 을 넣고 메세지 가공이나 받아온 메세지 자체에 대한 것은 도메인에 넣어도 될것같긴 한데요
사실 모두 도메인에 들어가도 상관없을것 같아요

'메세지 리슨'이라는 행위 자체를 도메인으로 볼 수도 있는거구요.

이런걸 판단 하는건 여러가지 관점이 있을 수 있는데
이건 어떠한 개체가 해당 서비스에서 어느정도의 중요도를 갖는가, 혹은 하나의 패키지에 다 몰아넣기가 가독성이 떨어지는가로도 판단 할 수 있을 것 같아요

어떤 책에서 (클린 아키텍처였는지 오브젝트였는지 생각이 안나네요...) 봤던 내용 중에 인상 깊었던 내용이 하나 있는데
아키텍처란 결국 소스코드를 배치 하는것의 어려운 말일 뿐이고,
소스코드를 어떻게 배치 하느냐에 따른 개발 편의성이나 안전성등에 어느정도 영향을 끼칠 수 있는가에 대한 이야기인데

패키지, 클래스를 잘 분리 하여 어떤 수정이 일어났을 때 수정의 범위를 해당 패키지 내로만 한정 짓게 하고, 어떤 장애가 생겼을 때 해당 장애 원인을 빠르게 파악 할 수 있는 레이어, 구조 등을 갖추는게 결국 좋은 아키텍처라는 말을 하는것 같더라구요.
혹은 이 소스를 처음 보는 신입 개발자가 빠르게 내용을 파악할수있느냐도 되겠네요.

이런걸 종합적으로 판단 해서 ... 메세지 리슨 자체를 도메인으로 볼 수도 있고 
혹은 뭐 지금 저희 서비스가 도메인 패키지에 비해 서비스가 너무 빈약하다. 도메인에만 너무 패키지가 많다. 라고 느끼시면 서비스에 넣어도 좋은것같아요

뭔가 두루뭉실하긴 한데 어쨌든 정답은 없고 종윤님이 생각 하시는것에 이유만 타당하다면 어느쪽이든 상관없을것같습니다!
