### ISSUE TITLE
실시간 인기 검색어 기능을 위한 로그 수집 전략 검토

### ISSUE THREAD

**Issue by 97e57e** [mash-up-kr/Elegant_Spring_Family_Search#3]
주기적 스케쥴링을 통한 로그 수집 vs filebeat 등을 이용한 실시간 로그 수집

**Comment by kh0712** [comment]
키워드 검색 컨트롤러에서 (시간, 검색어) DTO 만들어서 바로 저장해도 될 것같아요

**Comment by lee-garden** [comment]
@kh0712 
https://niiiii99.github.io/elasticsearch-logback-appender-%EC%A0%81%EC%9A%A9/

logback에 appender 라는게 있는데 로그가 찍히면 자동으로 목적지로 보내주는 기능이에요.
kafka appender, sentry appender등 여러가지 종류가 있는데 찾아보니 elasticsearch appender도 있네요

검색로그를 elasticsearch에 저장 한다면 elastic search appender를 사용해도 좋을것같아요
커스텀 필터를 통해서 로직을 첨가 할 수도 있고 포맷도 원하는대로 만들어 줄 수 있습니다

**Comment by lee-garden** [comment]
@kh0712 
찾아보니 저 글에서 언급한 elasticsearch appender는 현재 관리 되고 있지 않네요 마지막 커밋도 4년 전이고 ...

공식 지원이 아닌 외부에서 만든건가봐요 logback appender중 es에 로그를 적재할 수 있는것 중 공식적으로 지원하는건
logstash, fluentd 정도가 있어서 logstash나 fluentd를 띄워야할 것 같아요. (물론 elasticsearch appender 써도 되긴 하지만 찝찝하네요 ㅋㅋ)

docker compose 같은걸로 띄워도 될것 같고 그냥 따로 인스턴스 띄워서 거기에 띄워둬도 될것같은데 현재 인프라 상황으로썬 따로 띄우는게 나을것 같긴 해요 아마존은 아마 프리티어로 더 못쓸것같은데 공용 구글 계정으로 gcp 가입해서 쓰거나.. 방법은 좀 더 고민해볼게요 ㅎ

**Comment by lee-garden** [comment]
spring boot + logback + elasticsearch로 연동 성공.
