### ISSUE TITLE
Elasticsearch 인스턴스 띄우기

### ISSUE THREAD

**Issue by 97e57e** [mash-up-kr/Elegant_Spring_Family_Search#6]

**Comment by 97e57e** [comment]
도메인 : https://search-mashup-spring-search-5stojescxljz22frzubuuqpauu.ap-northeast-2.es.amazonaws.com

참고 : https://www.notion.so/a2efd3f50eab40599df4cac733a262c0

**Comment by junhaesung** [comment]
오.. AWS 에 ElasticSearch Service 도 있군요. 정말 없는게 없네요 ㅋㅋ
